version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  server:
    build: ./server
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  redis_data: 